# Enables all default rules
default: true

# MD013: Maximum line length (100 characters)
MD013:
  line_length: 100
  code_blocks: false  # Ignore code blocks when checking line length
  headings: false  # Allow headers to exceed line length (they will wrap)

# MD029: Ordered list style
MD029:
  style: ordered # Enforce 1., 2., 3., etc.

# MD033: No inline HTML
MD033: false  # allow inline HTML

# MD041: Require a top-level heading
MD041: true

# MD044: Enforce specific capitalization/spelling for words
MD044:
  names: # List of words that must be capitalized exactly as written
    - HTML
    - CSS
    - JAVASCRIPT
    - TYPESCRIPT
    - JSON
